# Generated by Django 2.0.7 on 2018-09-03 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Partner id')),
                ('name', models.CharField(max_length=128)),
                ('users', models.ManyToManyField(related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
